{-# LANGUAGE RecordWildCards #-}
module Events where

import qualified Data.ByteString as BS
import Data.ByteString (ByteString)
import qualified Data.ByteString.Char8 as BS8
import qualified Data.ByteString.Builder as B
import Data.ByteString.Builder (Builder)
import Data.Word

bus_usb :: Word16
bus_usb = 0x03

ui_set_evbit :: Int
ui_set_evbit   = 1074025828
ui_set_keybit :: Int
ui_set_keybit  = 1074025829

ui_dev_setup :: Int
ui_dev_setup = 1079792899
ui_dev_create :: Int
ui_dev_create = 21761
ui_dev_destroy :: Int
ui_dev_destroy = 21762

ev_syn         :: Int
ev_syn         = 0x00
ev_key         :: Int
ev_key         = 0x01

syn_report     :: Int
syn_report     = 0

key_esc         :: Int
key_esc        = 1
key_1         :: Int
key_1          = 2
key_2         :: Int
key_2          = 3
key_3         :: Int
key_3          = 4
key_4         :: Int
key_4          = 5
key_5         :: Int
key_5          = 6
key_6         :: Int
key_6          = 7
key_7         :: Int
key_7          = 8
key_8         :: Int
key_8          = 9
key_9         :: Int
key_9          = 10
key_0         :: Int
key_0          = 11
key_minus         :: Int
key_minus      = 12
key_equal         :: Int
key_equal      = 13
key_backspace         :: Int
key_backspace  = 14
key_tab         :: Int
key_tab        = 15
key_q         :: Int
key_q          = 16
key_w         :: Int
key_w          = 17
key_e         :: Int
key_e          = 18
key_r         :: Int
key_r          = 19
key_t         :: Int
key_t          = 20
key_y         :: Int
key_y          = 21
key_u         :: Int
key_u          = 22
key_i         :: Int
key_i          = 23
key_o         :: Int
key_o          = 24
key_p         :: Int
key_p          = 25
key_leftbrace         :: Int
key_leftbrace  = 26
key_rightbrace         :: Int
key_rightbrace = 27
key_enter         :: Int
key_enter      = 28
key_leftctrl         :: Int
key_leftctrl   = 29
key_a         :: Int
key_a          = 30
key_s         :: Int
key_s          = 31
key_d         :: Int
key_d          = 32
key_f         :: Int
key_f          = 33
key_g         :: Int
key_g          = 34
key_h         :: Int
key_h          = 35
key_j         :: Int
key_j          = 36
key_k         :: Int
key_k          = 37
key_l         :: Int
key_l          = 38
key_semicolon         :: Int
key_semicolon  = 39
key_apostrophe         :: Int
key_apostrophe = 40
key_grave         :: Int
key_grave      = 41
key_leftshift         :: Int
key_leftshift  = 42
key_backslash         :: Int
key_backslash  = 43
key_z         :: Int
key_z          = 44
key_x         :: Int
key_x          = 45
key_c         :: Int
key_c          = 46
key_v         :: Int
key_v          = 47
key_b         :: Int
key_b          = 48
key_n         :: Int
key_n          = 49
key_m         :: Int
key_m          = 50
key_comma         :: Int
key_comma      = 51
key_dot         :: Int
key_dot        = 52
key_slash         :: Int
key_slash      = 53
key_rightshift         :: Int
key_rightshift = 54
key_kpasterisk         :: Int
key_kpasterisk = 55
key_leftalt         :: Int
key_leftalt    = 56
key_space         :: Int
key_space      = 57
key_capslock         :: Int
key_capslock   = 58
key_f1         :: Int
key_f1         = 59
key_f2         :: Int
key_f2         = 60
key_f3         :: Int
key_f3         = 61
key_f4         :: Int
key_f4         = 62
key_f5         :: Int
key_f5         = 63
key_f6         :: Int
key_f6         = 64
key_f7         :: Int
key_f7         = 65
key_f8         :: Int
key_f8         = 66
key_f9         :: Int
key_f9         = 67
key_f10         :: Int
key_f10        = 68
key_numlock         :: Int
key_numlock    = 69
key_scrolllock         :: Int
key_scrolllock = 70
key_kp7         :: Int
key_kp7        = 71
key_kp8         :: Int
key_kp8        = 72
key_kp9         :: Int
key_kp9        = 73
key_kpminus         :: Int
key_kpminus    = 74
key_kp4         :: Int
key_kp4        = 75
key_kp5         :: Int
key_kp5        = 76
key_kp6         :: Int
key_kp6        = 77
key_kpplus         :: Int
key_kpplus     = 78
key_kp1         :: Int
key_kp1        = 79
key_kp2         :: Int
key_kp2        = 80
key_kp3         :: Int
key_kp3        = 81
key_kp0         :: Int
key_kp0        = 82
key_kpdot         :: Int
key_kpdot      = 83
